### PR TITLE
0.7 release

### PR DESCRIPTION
**Pull request by DenisFrezzato**
Closes https://github.com/DenisFrezzato/hyper-ts/issues/50

### CODE REVIEW

**Comment by mlegenhausen** [comment]
@DenisFrezzato could you release a `next` or `rc` version? That would help by testing it in my code base.

**Comment by DenisFrezzato** [comment]
@mlegenhausen good idea, I've just released `0.7.0-rc.1`.

**Comment by DenisFrezzato** [comment]
@mlegenhausen do you have any feedback? I've tried it in a couple of projects and I haven't found any issue.

@kylegoetz what about you, have you tried the indexed functions?

**Comment by kylegoetz** [comment]
@DenisFrezzato I have not yet because I haven't upgraded hyper-ts. I need to check for any breaking changes and upgrade if there aren't any.

**Comment by mlegenhausen** [comment]
@DenisFrezzato No upgrade issues and works like a charm. Good work!

**Pull request merged**
